/**
 * AGENTS.md Generator
 * Auto-generate agent configuration from installed skills
 */

import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import YAML from 'yaml';
import type { SkillLocation, AGENTSMDSkill, SyncOptions } from './types.js';

export class AGENTSMDGenerator {
  private projectRoot: string;

  constructor(projectRoot: string = process.cwd()) {
    this.projectRoot = projectRoot;
  }

  /**
   * Generate AGENTS.md content
   */
  generateAGENTSMD(skills: SkillLocation[]): string {
    if (skills.length === 0) {
      return this.getEmptyTemplate();
    }

    const skillsXML = skills
      .map((skill) => {
        const metadata = this.getSkillMetadata(skill);
        return this.formatSkillXML(metadata);
      })
      .join('\n');

    return `# Agent Configuration

<available_skills>
${skillsXML}
</available_skills>

## Usage

The above skills are available for this project. To use a skill:

1. Skills are discovered automatically by the IDE
2. Skills with SKILL.md format provide progressive disclosure
3. Skills can be invoked via the SkillKit CLI: \`tsk run <skill-name>\`

## Installed Locations

Skills are installed in priority order:
1. \`./.agent/skills/\` (project universal)
2. \`~/.agent/skills/\` (global universal)
3. \`./.claude/skills/\` (project)
4. \`~/.claude/skills/\` (global)

This file was auto-generated by SkillKit. Run \`tsk sync\` to update.
`;
  }

  /**
   * Get empty AGENTS.md template
   */
  private getEmptyTemplate(): string {
    return `# Agent Configuration

<available_skills>
<!-- No skills installed yet -->
<!-- Install skills with: tsk install <repo> -->
</available_skills>

## Getting Started

To add skills to your project:

1. Install skills from GitHub:
   \`\`\`bash
   tsk install anthropics/skills  # Interactive selection
   tsk install anthropics/skills --all  # Install all
   \`\`\`

2. Run \`tsk sync\` to update this file

3. List installed skills:
   \`\`\`bash
   tsk list
   \`\`\`

This file was auto-generated by SkillKit. Run \`tsk sync\` to update.
`;
  }

  /**
   * Format skill as XML
   */
  private formatSkillXML(skill: AGENTSMDSkill): string {
    return `  <skill>
    <name>${this.escapeXML(skill.name)}</name>
    <description>${this.escapeXML(skill.description)}</description>
  </skill>`;
  }

  /**
   * Get skill metadata from SKILL.md or SKILL.yaml
   */
  private getSkillMetadata(skill: SkillLocation): AGENTSMDSkill {
    const skillMdPath = path.join(skill.path, 'SKILL.md');
    const skillYamlPath = path.join(skill.path, 'SKILL.yaml');

    let metadata: Record<string, unknown> = { name: skill.name, description: 'No description' };

    // Try SKILL.md first
    if (fs.existsSync(skillMdPath)) {
      try {
        const content = fs.readFileSync(skillMdPath, 'utf-8');
        const parsed = matter(content);
        metadata = { ...metadata, ...parsed.data };
      } catch {
        // Fall through to default
      }
    }
    // Try SKILL.yaml
    else if (fs.existsSync(skillYamlPath)) {
      try {
        const content = fs.readFileSync(skillYamlPath, 'utf-8');
        const parsed = YAML.parse(content);
        metadata = { ...metadata, ...parsed };
      } catch {
        // Fall through to default
      }
    }

    return {
      name: (typeof metadata['name'] === 'string' ? metadata['name'] : skill.name),
      description: (typeof metadata['description'] === 'string' ? metadata['description'] : 'No description'),
      location: 'project',
    };
  }

  /**
   * Parse existing AGENTS.md to get current skills
   */
  parseExistingAGENTSMD(filePath: string): string[] {
    if (!fs.existsSync(filePath)) {
      return [];
    }

    try {
      const content = fs.readFileSync(filePath, 'utf-8');

      // Extract skill names from XML
      const skillNameRegex = /<name>(.*?)<\/name>/g;
      const matches = Array.from(content.matchAll(skillNameRegex));

      return matches.map((match) => match[1].trim());
    } catch {
      return [];
    }
  }

  /**
   * Write AGENTS.md file
   */
  async writeAGENTSMD(skills: SkillLocation[], options: SyncOptions = {}): Promise<void> {
    const { output = path.join(this.projectRoot, 'AGENTS.md') } = options;

    const content = this.generateAGENTSMD(skills);

    // Ensure directory exists
    const dir = path.dirname(output);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(output, content, 'utf-8');
  }

  /**
   * Escape XML special characters
   */
  private escapeXML(str: string): string {
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&apos;');
  }
}

